name: Entregables

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - name: Paso 1 - Checkout en Repositorio
      uses: actions/checkout@v4
    - name: Paso 2 - Setup python
      uses: actions/setup-python@vs
      with: 
        python-version: '3.9.2'
    - name: Paso 3 - Crear entorno virtual
      run: python -m venv venv 
    - name: Paso 4 - Activar entorno virtual
      run: ./venv/scripts/activate
    - name: Paso 5 - Ejecutar Script
      run: python hello.py  
